version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    assignees:
      - "cristianglezm"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    assignees:
      - cristianglezm
