groups:
  - name: fe_describe_alerts
    interval: 30s
    rules:
      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{status_code=~"5.."}[5m])) 
              / sum(rate(http_requests_total[5m])) * 100 > 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% for the last 2 minutes."

      - alert: HighLatencyP99
        expr: histogram_quantile(0.99, sum(rate(http_request_latency_seconds_bucket[5m])) by (le)) > 2
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High latency (p99)"
          description: "p99 latency is above 2 seconds for the last 2 minutes."

  - name: kafka_alerts
    interval: 30s
    rules:
      - alert: KafkaConsumerLag
        expr: sum(kafka_consumergroup_lag) > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Kafka consumer lag high"
          description: "Consumer lag is above 1000 messages."

  - name: redis_alerts
    interval: 30s
    rules:
      - alert: RedisMemoryUsageHigh
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.8
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Redis memory usage high"
          description: "Redis memory usage is above 80%."
